version: "3.5"
services:
  toncat:   
    ports: 
      - "8081:8081"
    container_name: tomcat
    build: 
      dockerfile: .
      context: .
    volumes:
          - ./mount/webapps:/usr/local/tomcat/webapps
    networks:
      - minha-rede
   
volumes:
  tomcat-volume:


networks: 
  minha-rede:
    name: minha-rede
    driver: bridge

