spring:
  profile: dev
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alura_spring_boot
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
  boot:
    admin:
      client:
        url: 'http://localhost:8081'

token:
  secret: chavedotoken
  expiration: 86400000

#   actuator configuration
management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'
info:
  app:
    description: Alura Spring Course course
    version: 1.0
    encoding: UTF-8
    java:
      version: 1.8.0_275

